import { Superhero } from './superheroes.model';

export const superheroes: Superhero[] = [
  { name: 'Iron Man', superpower: 'Technology', humilityScore: 7 },
  { name: 'Spider-Man', superpower: 'Agility', humilityScore: 9 },
  { name: 'Captain America', superpower: 'Super Soldier', humilityScore: 10 },
  { name: 'Thor', superpower: 'Thunder', humilityScore: 8 },
  { name: 'Hulk', superpower: 'Strength', humilityScore: 6 },
  { name: 'Black Widow', superpower: 'Espionage', humilityScore: 8 },
  { name: 'Doctor Strange', superpower: 'Magic', humilityScore: 7 },
  { name: 'Black Panther', superpower: 'Vibranium Suit', humilityScore: 9 },
  { name: 'Scarlet Witch', superpower: 'Reality Manipulation', humilityScore: 5 },
  { name: 'Ant-Man', superpower: 'Size Manipulation', humilityScore: 8 },
  { name: 'Wolverine', superpower: 'Regeneration and Claws', humilityScore: 7 },
  { name: 'Deadpool', superpower: 'Immortality', humilityScore: 4 },
  { name: 'Cyclops', superpower: 'Optic Blast', humilityScore: 6 },
  { name: 'Storm', superpower: 'Weather Control', humilityScore: 8 },
  { name: 'Jean Grey', superpower: 'Telekinesis and Telepathy', humilityScore: 5 },
  { name: 'Beast', superpower: 'Super Strength and Agility', humilityScore: 8 },
  { name: 'Gambit', superpower: 'Kinetic Energy Manipulation', humilityScore: 7 },
  { name: 'Rogue', superpower: 'Power Absorption', humilityScore: 6 },
  { name: 'Vision', superpower: 'Density Manipulation', humilityScore: 9 },
  { name: 'Falcon', superpower: 'Flight and Combat', humilityScore: 7 },
  { name: 'Hawkeye', superpower: 'Marksmanship', humilityScore: 8 },
  { name: 'Winter Soldier', superpower: 'Enhanced Soldier', humilityScore: 6 },
  { name: 'War Machine', superpower: 'Armored Suit', humilityScore: 7 },
  { name: 'Nick Fury', superpower: 'Espionage', humilityScore: 8 },
  { name: 'Loki', superpower: 'Trickery and Magic', humilityScore: 5 },
  { name: 'Gamora', superpower: 'Combat Skills', humilityScore: 7 },
  { name: 'Star-Lord', superpower: 'Leadership and Gadgets', humilityScore: 6 },
  { name: 'Rocket Raccoon', superpower: 'Tactical Genius', humilityScore: 7 },
  { name: 'Groot', superpower: 'Regrowth and Strength', humilityScore: 8 },
  { name: 'Drax', superpower: 'Super Strength', humilityScore: 6 },
  { name: 'Nebula', superpower: 'Enhanced Assassin', humilityScore: 5 },
  { name: 'Mantis', superpower: 'Empathy and Combat', humilityScore: 8 },
  { name: 'Shuri', superpower: 'Technological Genius', humilityScore: 9 },
  { name: 'Okoye', superpower: 'Combat Mastery', humilityScore: 8 },
  { name: 'Yondu', superpower: 'Arrow Control', humilityScore: 7 },
  { name: 'Elektra', superpower: 'Martial Arts Master', humilityScore: 6 },
  { name: 'Daredevil', superpower: 'Super Senses', humilityScore: 8 },
  { name: 'Jessica Jones', superpower: 'Super Strength', humilityScore: 7 },
  { name: 'Luke Cage', superpower: 'Invulnerability', humilityScore: 7 },
  { name: 'Iron Fist', superpower: 'Chi-Powered Fist', humilityScore: 7 },
  { name: 'Moon Knight', superpower: 'Enhanced Abilities', humilityScore: 6 },
  { name: 'The Punisher', superpower: 'Vengeance and Combat', humilityScore: 5 },
  { name: 'Quicksilver', superpower: 'Super Speed', humilityScore: 6 },
  { name: 'Scarlet Spider', superpower: 'Agility and Web-Slinging', humilityScore: 8 },
  { name: 'Silver Surfer', superpower: 'Cosmic Power', humilityScore: 9 },
  { name: 'Nova', superpower: 'Energy Manipulation', humilityScore: 8 },
  { name: 'Adam Warlock', superpower: 'Cosmic Power', humilityScore: 10 },
  { name: 'The Wasp', superpower: 'Size Manipulation and Flight', humilityScore: 8 },
  { name: 'Captain Marvel', superpower: 'Cosmic Energy', humilityScore: 9 },
  { name: 'Sentry', superpower: 'Molecular Manipulation', humilityScore: 8 },
];
